// Generated by tools/generate-shared-contracts.py. Do not edit.

import Foundation

public enum HozzArchiveContract {
    public static let schemaVersion = 1
    public static let manifestEntry = "hozz-manifest.json"
    public static let format = "hozz-ndjson"
    public static let recordSchema = "hozz/v1/canonical-record"
    public static let healthConnectPackage = "com.thatcube.hozz"

    public static let healthConnectMappedTypes: Set<String> = [
        "HKQuantityTypeIdentifierStepCount",
        "HKQuantityTypeIdentifierHeartRate",
        "HKQuantityTypeIdentifierBodyMass",
        "HKQuantityTypeIdentifierHeight",
        "HKCategoryTypeIdentifierSleepAnalysis",
        "HKQuantityTypeIdentifierDistanceWalkingRunning",
        "HKQuantityTypeIdentifierActiveEnergyBurned",
        "HKWorkoutTypeIdentifier",
    ]

    public static let canonicalTypesBySourceIdentifier: [String: String] = [
        "HKQuantityTypeIdentifierStepCount": "activity.steps",
        "HKQuantityTypeIdentifierHeartRate": "vitals.heart-rate",
        "HKQuantityTypeIdentifierBodyMass": "body.weight",
        "HKQuantityTypeIdentifierHeight": "body.height",
        "HKCategoryTypeIdentifierSleepAnalysis": "sleep.stage",
        "HKQuantityTypeIdentifierDistanceWalkingRunning": "activity.distance",
        "HKQuantityTypeIdentifierActiveEnergyBurned": "energy.active",
        "HKWorkoutTypeIdentifier": "activity.exercise-session",
    ]

    public static let archiveOnlyKinds: Set<String> = [
        "audiogram",
        "characteristics",
        "clinicalRecord",
        "correlation",
        "electrocardiogram",
        "electrocardiogramEnd",
        "electrocardiogramVoltages",
        "medicationDose",
        "quantitySeriesEnd",
        "quantitySeriesReadings",
        "sampleEncodingError",
        "sample",
        "stateOfMind",
        "workoutRoute",
        "workoutRouteEnd",
        "workoutRouteLocations",
    ]

    public static let archiveOnlyCanonicalTypes: [String: String] = [
        "audiogram": "hearing.audiogram",
        "characteristics": "person.characteristics",
        "clinicalRecord": "clinical.record",
        "correlation": "archive.correlation",
        "electrocardiogram": "cardiac.electrocardiogram",
        "electrocardiogramEnd": "cardiac.electrocardiogram-end",
        "electrocardiogramVoltages": "cardiac.electrocardiogram-waveform",
        "medicationDose": "medication.dose",
        "quantitySeriesEnd": "series.end",
        "quantitySeriesReadings": "series.readings",
        "sample": "archive.raw",
        "sampleEncodingError": "archive.encoding-error",
        "stateOfMind": "mind.state",
        "workoutRoute": "activity.exercise-route",
        "workoutRouteEnd": "activity.exercise-route-end",
        "workoutRouteLocations": "activity.exercise-route-locations",
    ]
    public static let sourceCanonicalTypes: [String: String] = [
        "HKDataTypeIdentifierAudiogram": "hearing.audiogram",
        "HKDataTypeIdentifierElectrocardiogram": "cardiac.electrocardiogram",
        "HKDataTypeStateOfMind": "mind.state",
        "HKMedicationDoseEventTypeIdentifierMedicationDoseEvent": "medication.dose",
        "HKWorkoutRouteTypeIdentifier": "activity.exercise-route",
    ]
    public static let sourceCanonicalTypePrefixes: [String: String] = [
        "HKClinicalTypeIdentifier": "clinical.record",
    ]
}
