import Foundation
@testable import HozzDeliver
import HozzStore
import XCTest

/// Whether a payload can be taken apart and put back together without a record
/// changing, disappearing, or arriving twice.
///
/// Every payload in this file is written out by hand in the exact shape the
/// builders produce, never generated by calling the code under test. A test that
/// encodes with `recompose` and then checks `decompose` agrees proves only that
/// one function is the inverse of the other, which is true of any pair of
/// mistakes made consistently.
final class PayloadDivisionTests: XCTestCase {
    // MARK: - Fixtures, written by hand

    private let ndjson = Data(
        """
        {"id":"a","kind":"quantity","startDate":"2026-08-20T09:00:00.000Z","type":"HKQuantityTypeIdentifierStepCount"}
        {"id":"b","kind":"quantity","startDate":"2026-08-21T09:00:00.000Z","type":"HKQuantityTypeIdentifierStepCount"}
        {"id":"c","kind":"quantity","startDate":"2026-08-22T09:00:00.000Z","type":"HKQuantityTypeIdentifierStepCount"}

        """.utf8
    )

    private let json = Data(
        """
        [
        {"id":"a","kind":"quantity","startDate":"2026-08-20T09:00:00.000Z"},
        {"id":"b","kind":"quantity","startDate":"2026-08-21T09:00:00.000Z"},
        {"id":"c","kind":"quantity","startDate":"2026-08-22T09:00:00.000Z"}
        ]

        """.utf8
    )

    private let csv = Data(
        """
        id,type,kind,startDate,endDate,value,unit,sourceName,deleted
        a,HKQuantityTypeIdentifierStepCount,quantity,2026-08-20T09:00:00.000Z,2026-08-20T09:00:00.000Z,120,count,Watch,false
        b,HKQuantityTypeIdentifierStepCount,quantity,2026-08-21T09:00:00.000Z,2026-08-21T09:00:00.000Z,240,count,"Brandon's iPhone, work",false
        c,HKQuantityTypeIdentifierStepCount,quantity,2026-08-22T09:00:00.000Z,2026-08-22T09:00:00.000Z,360,count,Watch,false

        """.utf8
    )

    private let influx = Data(
        """
        health,type=step_count,unit=count value=120.0 1787216400000000000
        health,type=step_count,unit=count value=240.0 1787302800000000000
        health,type=step_count,unit=count value=360.0 1787389200000000000

        """.utf8
    )

    /// Sorted keys, no spaces — the shape `JSONSerialization` writes with
    /// `.sortedKeys` and `.withoutEscapingSlashes`, which is what the builder
    /// uses.
    private let metrics = Data(
        #"{"data":{"metrics":[{"data":[{"date":"2026-08-20T09:00:00.000Z","qty":120},{"date":"2026-08-22T09:00:00.000Z","qty":360}],"name":"step_count","units":"count"}]}}"#
            .utf8
    )

    // MARK: - Nothing changes on the way through

    func testEveryFormatRoundTripsToTheSameBytes() {
        let cases: [(DeliveryFormat, Data)] = [
            (.ndjson, ndjson),
            (.json, json),
            (.csv, csv),
            (.influx, influx),
            (.metrics, metrics)
        ]
        for (format, payload) in cases {
            XCTAssertTrue(
                PayloadDivision.roundTripsExactly(payload, format: format),
                "\(format.rawValue) did not come back byte for byte."
            )
        }
    }

    func testRecordCountsMatchWhatWasWrittenByHand() {
        let expected: [(DeliveryFormat, Data, Int)] = [
            (.ndjson, ndjson, 3),
            (.json, json, 3),
            (.csv, csv, 3),
            (.influx, influx, 3),
            (.metrics, metrics, 2)
        ]
        for (format, payload, count) in expected {
            XCTAssertEqual(
                PayloadDivision.decompose(payload, format: format)?.count,
                count,
                "\(format.rawValue) counted its records wrongly."
            )
        }
    }

    // MARK: - Splitting loses nothing and repeats nothing

    /// The identifiers are read back out of the parts and compared against the
    /// list written at the top of this file — not against whatever the splitter
    /// happened to produce.
    func testSplittingKeepsEveryRecordExactlyOnce() {
        let parts = PayloadDivision.divide(ndjson, format: .ndjson, into: 2)

        XCTAssertEqual(parts.count, 2, "Three records in twos is two parts.")
        XCTAssertEqual(identifiers(inNDJSON: parts[0]), ["a", "b"])
        XCTAssertEqual(identifiers(inNDJSON: parts[1]), ["c"])
        XCTAssertEqual(
            parts.flatMap(identifiers(inNDJSON:)),
            ["a", "b", "c"],
            "Every record, in order, once."
        )
    }

    func testEveryPartIsAValidPayloadOfTheSameFormat() throws {
        let parts = PayloadDivision.divide(json, format: .json, into: 2)

        for part in parts {
            let array = try JSONSerialization.jsonObject(with: part) as? [Any]
            XCTAssertNotNil(array, "A JSON part has to still be a JSON array.")
        }
        XCTAssertEqual(
            try parts.flatMap { part in
                try XCTUnwrap(
                    JSONSerialization.jsonObject(with: part) as? [[String: Any]]
                ).map { $0["id"] as? String ?? "" }
            },
            ["a", "b", "c"]
        )
    }

    /// The header is not a record, and a part without it is a file nothing can
    /// read.
    func testEveryCSVPartCarriesTheHeaderRow() {
        let parts = PayloadDivision.divide(csv, format: .csv, into: 1)

        XCTAssertEqual(parts.count, 3)
        for part in parts {
            let text = String(decoding: part, as: UTF8.self)
            XCTAssertTrue(
                text.hasPrefix("id,type,kind,startDate,"),
                "A CSV part has to name its columns: \(text)"
            )
            XCTAssertEqual(
                text.split(separator: "\n").count,
                2,
                "One header and one record: \(text)"
            )
        }
    }

    func testSplittingMetricsJSONKeepsThePointsAndTheirMetric() throws {
        let parts = PayloadDivision.divide(metrics, format: .metrics, into: 1)

        XCTAssertEqual(parts.count, 2)
        var quantities: [Double] = []
        for part in parts {
            let root = try XCTUnwrap(
                JSONSerialization.jsonObject(with: part) as? [String: Any]
            )
            let data = try XCTUnwrap(root["data"] as? [String: Any])
            let list = try XCTUnwrap(data["metrics"] as? [[String: Any]])
            XCTAssertEqual(list.count, 1)
            XCTAssertEqual(list[0]["name"] as? String, "step_count")
            XCTAssertEqual(list[0]["units"] as? String, "count")
            let points = try XCTUnwrap(list[0]["data"] as? [[String: Any]])
            quantities.append(contentsOf: points.compactMap { $0["qty"] as? Double })
        }
        XCTAssertEqual(quantities, [120, 360], "Both points, neither twice.")
    }

    func testAPayloadSmallerThanTheLimitIsNotTouched() {
        XCTAssertEqual(
            PayloadDivision.divide(ndjson, format: .ndjson, into: 10),
            [ndjson]
        )
    }

    // MARK: - Dates come back the way they went in

    func testNDJSONDatesAreReadFromTheRecord() throws {
        let division = try XCTUnwrap(
            PayloadDivision.decompose(ndjson, format: .ndjson)
        )
        // 2026-08-20T09:00:00Z, computed here rather than parsed by the code
        // under test.
        var components = DateComponents()
        components.year = 2026
        components.month = 8
        components.day = 20
        components.hour = 9
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "UTC")!

        XCTAssertEqual(division.records[0].date, calendar.date(from: components))
    }

    /// A source name containing a comma is a name someone can actually set, and
    /// splitting on commas would read the wrong column as the date.
    func testCSVDatesSurviveAQuotedFieldContainingAComma() throws {
        let division = try XCTUnwrap(PayloadDivision.decompose(csv, format: .csv))
        let dates = division.records.compactMap(\.date)

        XCTAssertEqual(dates.count, 3, "Every row must be dated, including the quoted one.")
        XCTAssertEqual(
            dates[1].timeIntervalSince(dates[0]),
            86_400,
            accuracy: 0.001,
            "Consecutive days are a day apart."
        )
    }

    func testCSVFieldsAreSplitWithQuotingHonoured() {
        XCTAssertEqual(
            PayloadDivision.csvFields(#"a,b,"c,d",e"#),
            ["a", "b", "c,d", "e"]
        )
        XCTAssertEqual(
            PayloadDivision.csvFields(#"a,"say ""hi""",b"#),
            ["a", #"say "hi""#, "b"]
        )
    }

    /// The timestamp was written in the destination's precision, so reading it
    /// back in a different one would place every point in the wrong decade.
    func testInfluxTimestampsAreReadInTheDeclaredPrecision() throws {
        // 1787216400 seconds after 1970 is 2026-08-20T09:00:00Z, worked out
        // independently rather than by asking Hozz what it thinks.
        let nanoseconds = try XCTUnwrap(
            PayloadDivision.decompose(
                influx,
                format: .influx,
                influxPrecision: .nanoseconds
            )
        )
        XCTAssertEqual(
            try XCTUnwrap(nanoseconds.records[0].date).timeIntervalSince1970,
            1_787_216_400,
            accuracy: 0.001
        )

        // The same instant written in milliseconds. Reading it as nanoseconds
        // would file it in 1970, which InfluxDB accepts without complaint.
        let milliseconds = Data("health value=1 1787216400000\n".utf8)
        let read = try XCTUnwrap(
            PayloadDivision.decompose(
                milliseconds,
                format: .influx,
                influxPrecision: .milliseconds
            )
        )
        XCTAssertEqual(
            try XCTUnwrap(read.records[0].date).timeIntervalSince1970,
            1_787_216_400,
            accuracy: 0.001
        )
    }

    /// A tombstone carries no date at all. Reading one as undated rather than as
    /// dated to 1970 is what keeps a window from throwing it away.
    func testARecordWithNoDateIsUndatedRatherThanDatedWrongly() throws {
        let tombstone = Data(
            """
            {"id":"gone","kind":"deletion","schemaVersion":1,"type":"HKQuantityTypeIdentifierStepCount"}

            """.utf8
        )
        let division = try XCTUnwrap(
            PayloadDivision.decompose(tombstone, format: .ndjson)
        )
        XCTAssertEqual(division.count, 1)
        XCTAssertNil(division.records[0].date)
    }

    // MARK: - Refusing rather than guessing

    func testAPayloadThisCannotReadIsRefusedRatherThanSplitAtRandom() {
        let notJSON = Data("this is not a record\nnor is this\n".utf8)

        XCTAssertNil(PayloadDivision.decompose(notJSON, format: .ndjson))
        XCTAssertEqual(
            PayloadDivision.divide(notJSON, format: .ndjson, into: 1),
            [notJSON],
            "A payload that cannot be divided is sent whole, not cut in half."
        )
    }
}

private func identifiers(inNDJSON payload: Data) -> [String] {
    payload
        .split(separator: 0x0A, omittingEmptySubsequences: true)
        .compactMap { slice -> String? in
            guard
                let object = try? JSONSerialization.jsonObject(with: Data(slice))
                    as? [String: Any]
            else {
                return nil
            }
            return object["id"] as? String
        }
}
