// Generated by tools/generate-healthkit-catalog.py. Do not edit.

import Foundation

enum GeneratedHealthTypeCatalog {
    static let entries: [HealthCatalogEntry] = [
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierAbdominalCramps",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierAcne",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierAppetiteChanges",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierAppleStandHour",
            family: .category,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent",
            family: .category,
            introduced: IOSVersion(major: 15, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierAudioExposureEvent",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 0),
            canonicalUnit: nil,
            isDeprecated: true
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierBladderIncontinence",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierBleedingAfterMenopause",
            family: .category,
            introduced: IOSVersion(major: 27, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierBleedingAfterPregnancy",
            family: .category,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierBleedingDuringPregnancy",
            family: .category,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierBloating",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierBreastPain",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierCervicalMucusQuality",
            family: .category,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierChestTightnessOrPain",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierChills",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierConstipation",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierContraceptive",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 3),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierCoughing",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierDiarrhea",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierDizziness",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierDrySkin",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierFainting",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierFatigue",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierFever",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierGeneralizedBodyAche",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHairLoss",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHandwashingEvent",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHeadache",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 2),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHeartburn",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHighHeartRateEvent",
            family: .category,
            introduced: IOSVersion(major: 12, minor: 2),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHotFlashes",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierHypertensionEvent",
            family: .category,
            introduced: IOSVersion(major: 26, minor: 2),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierInfrequentMenstrualCycles",
            family: .category,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierIntermenstrualBleeding",
            family: .category,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierIrregularHeartRhythmEvent",
            family: .category,
            introduced: IOSVersion(major: 12, minor: 2),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierIrregularMenstrualCycles",
            family: .category,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierLactation",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 3),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierLossOfSmell",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierLossOfTaste",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierLowCardioFitnessEvent",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 3),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierLowHeartRateEvent",
            family: .category,
            introduced: IOSVersion(major: 12, minor: 2),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierLowerBackPain",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierMemoryLapse",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierMenopausalState",
            family: .category,
            introduced: IOSVersion(major: 27, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierMenstrualFlow",
            family: .category,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierMindfulSession",
            family: .category,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierMoodChanges",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierNausea",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierNightSweats",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierOvulationTestResult",
            family: .category,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierPelvicPain",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding",
            family: .category,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierPregnancy",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 3),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierPregnancyTestResult",
            family: .category,
            introduced: IOSVersion(major: 15, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierProgesteroneTestResult",
            family: .category,
            introduced: IOSVersion(major: 15, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierProlongedMenstrualPeriods",
            family: .category,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierRunnyNose",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSexualActivity",
            family: .category,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierShortnessOfBreath",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSinusCongestion",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSkippedHeartbeat",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSleepAnalysis",
            family: .category,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSleepApneaEvent",
            family: .category,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSleepChanges",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierSoreThroat",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierToothbrushingEvent",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierVaginalDryness",
            family: .category,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierVomiting",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCategoryTypeIdentifierWheezing",
            family: .category,
            introduced: IOSVersion(major: 13, minor: 6),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCharacteristicTypeIdentifierActivityMoveMode",
            family: .characteristic,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCharacteristicTypeIdentifierBiologicalSex",
            family: .characteristic,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCharacteristicTypeIdentifierBloodType",
            family: .characteristic,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCharacteristicTypeIdentifierDateOfBirth",
            family: .characteristic,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCharacteristicTypeIdentifierFitzpatrickSkinType",
            family: .characteristic,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCharacteristicTypeIdentifierWheelchairUse",
            family: .characteristic,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierAllergyRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierClinicalNoteRecord",
            family: .clinical,
            introduced: IOSVersion(major: 16, minor: 4),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierConditionRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierCoverageRecord",
            family: .clinical,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierImmunizationRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierLabResultRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierMedicationRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierProcedureRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKClinicalTypeIdentifierVitalSignRecord",
            family: .clinical,
            introduced: IOSVersion(major: 12, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCorrelationTypeIdentifierBloodPressure",
            family: .correlation,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKCorrelationTypeIdentifierFood",
            family: .correlation,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKDocumentTypeIdentifierCDA",
            family: .document,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierActiveEnergyBurned",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "kcal",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAppleExerciseTime",
            family: .quantity,
            introduced: IOSVersion(major: 9, minor: 3),
            canonicalUnit: "min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAppleMoveTime",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 5),
            canonicalUnit: "min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAppleSleepingWristTemperature",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "degC",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAppleStandTime",
            family: .quantity,
            introduced: IOSVersion(major: 13, minor: 0),
            canonicalUnit: "min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAppleWalkingSteadiness",
            family: .quantity,
            introduced: IOSVersion(major: 15, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierAtrialFibrillationBurden",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBasalBodyTemperature",
            family: .quantity,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: "degC",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBasalEnergyBurned",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "kcal",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBloodAlcoholContent",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBloodGlucose",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "mg/dL",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBloodPressureDiastolic",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "mmHg",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBloodPressureSystolic",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "mmHg",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBodyFatPercentage",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBodyMass",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "kg",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBodyMassIndex",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierBodyTemperature",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "degC",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierCrossCountrySkiingSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierCyclingCadence",
            family: .quantity,
            introduced: IOSVersion(major: 17, minor: 0),
            canonicalUnit: "count/min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower",
            family: .quantity,
            introduced: IOSVersion(major: 17, minor: 0),
            canonicalUnit: "W",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierCyclingPower",
            family: .quantity,
            introduced: IOSVersion(major: 17, minor: 0),
            canonicalUnit: "W",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierCyclingSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 17, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryBiotin",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryCaffeine",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryCalcium",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryCarbohydrates",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryChloride",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryCholesterol",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryChromium",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryCopper",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryEnergyConsumed",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "kcal",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryFatMonounsaturated",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryFatPolyunsaturated",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryFatSaturated",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryFatTotal",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryFiber",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryFolate",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryIodine",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryIron",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryMagnesium",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryManganese",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryMolybdenum",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryNiacin",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryPantothenicAcid",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryPhosphorus",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryPotassium",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryProtein",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryRiboflavin",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietarySelenium",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietarySodium",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietarySugar",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryThiamin",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminA",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminB12",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminB6",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminC",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminD",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminE",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryVitaminK",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryWater",
            family: .quantity,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: "mL",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDietaryZinc",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "g",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceCrossCountrySkiing",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceCycling",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceDownhillSnowSports",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 2),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistancePaddleSports",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceRowing",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceSkatingSports",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceSwimming",
            family: .quantity,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceWalkingRunning",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierDistanceWheelchair",
            family: .quantity,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierElectrodermalActivity",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "S",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierEnvironmentalAudioExposure",
            family: .quantity,
            introduced: IOSVersion(major: 13, minor: 0),
            canonicalUnit: "dBASPL",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierEnvironmentalSoundReduction",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "dBASPL",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "appleEffortScore",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierFlightsClimbed",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierForcedExpiratoryVolume1",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "L",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierForcedVitalCapacity",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "L",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierHeadphoneAudioExposure",
            family: .quantity,
            introduced: IOSVersion(major: 13, minor: 0),
            canonicalUnit: "dBASPL",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierHeartRate",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "count/min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierHeartRateVariabilitySDNN",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 0),
            canonicalUnit: "ms",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierHeight",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierInhalerUsage",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierInsulinDelivery",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 0),
            canonicalUnit: "IU",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierLeanBodyMass",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "kg",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierNikeFuel",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages",
            family: .quantity,
            introduced: IOSVersion(major: 15, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierNumberOfTimesFallen",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierOxygenSaturation",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierPaddleSportsSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierPeakExpiratoryFlowRate",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "L/min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierPeripheralPerfusionIndex",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierPhysicalEffort",
            family: .quantity,
            introduced: IOSVersion(major: 17, minor: 0),
            canonicalUnit: "kcal/(kg*hr)",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierPushCount",
            family: .quantity,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRespiratoryRate",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRestingHeartRate",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 0),
            canonicalUnit: "count/min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRowingSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRunningGroundContactTime",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "ms",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRunningPower",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "W",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRunningSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRunningStrideLength",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierRunningVerticalOscillation",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "cm",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierSixMinuteWalkTestDistance",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierStairAscentSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierStairDescentSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierStepCount",
            family: .quantity,
            introduced: IOSVersion(major: 8, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierSwimmingStrokeCount",
            family: .quantity,
            introduced: IOSVersion(major: 10, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierTimeInDaylight",
            family: .quantity,
            introduced: IOSVersion(major: 17, minor: 0),
            canonicalUnit: "min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierUVExposure",
            family: .quantity,
            introduced: IOSVersion(major: 9, minor: 0),
            canonicalUnit: "count",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierUnderwaterDepth",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierVO2Max",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 0),
            canonicalUnit: "ml/(kg*min)",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWaistCircumference",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWalkingAsymmetryPercentage",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "%",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWalkingHeartRateAverage",
            family: .quantity,
            introduced: IOSVersion(major: 11, minor: 0),
            canonicalUnit: "count/min",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWalkingSpeed",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "m/s",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWalkingStepLength",
            family: .quantity,
            introduced: IOSVersion(major: 14, minor: 0),
            canonicalUnit: "m",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWaterTemperature",
            family: .quantity,
            introduced: IOSVersion(major: 16, minor: 0),
            canonicalUnit: "degC",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKQuantityTypeIdentifierWorkoutEffortScore",
            family: .quantity,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: "appleEffortScore",
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKScoredAssessmentTypeIdentifierGAD7",
            family: .scoredAssessment,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
        HealthCatalogEntry(
            identifier: "HKScoredAssessmentTypeIdentifierPHQ9",
            family: .scoredAssessment,
            introduced: IOSVersion(major: 18, minor: 0),
            canonicalUnit: nil,
            isDeprecated: false
        ),
    ]
}
