// Generated by tools/generate-shared-contracts.py. Do not edit.

enum HozzHealthArchiveContract {
    static let schemaVersion = 1
    static let manifestEntry = "hozz-manifest.json"
    static let format = "hozz-ndjson"
    static let recordSchema = "hozz/v1/canonical-record"
    static let sourceStore = "apple.healthkit"
    static let canonicalTypesBySourceIdentifier: [String: String] = [
        "HKQuantityTypeIdentifierStepCount": "activity.steps",
        "HKQuantityTypeIdentifierHeartRate": "vitals.heart-rate",
        "HKQuantityTypeIdentifierBodyMass": "body.weight",
        "HKQuantityTypeIdentifierHeight": "body.height",
        "HKCategoryTypeIdentifierSleepAnalysis": "sleep.stage",
        "HKQuantityTypeIdentifierDistanceWalkingRunning": "activity.distance",
        "HKQuantityTypeIdentifierActiveEnergyBurned": "energy.active",
        "HKWorkoutTypeIdentifier": "activity.exercise-session",
    ]
    static let archiveOnlyCanonicalTypes: [String: String] = [
        "audiogram": "hearing.audiogram",
        "characteristics": "person.characteristics",
        "clinicalRecord": "clinical.record",
        "correlation": "archive.correlation",
        "electrocardiogram": "cardiac.electrocardiogram",
        "electrocardiogramEnd": "cardiac.electrocardiogram-end",
        "electrocardiogramVoltages": "cardiac.electrocardiogram-waveform",
        "medicationDose": "medication.dose",
        "quantitySeriesEnd": "series.end",
        "quantitySeriesReadings": "series.readings",
        "sample": "archive.raw",
        "sampleEncodingError": "archive.encoding-error",
        "stateOfMind": "mind.state",
        "workoutRoute": "activity.exercise-route",
        "workoutRouteEnd": "activity.exercise-route-end",
        "workoutRouteLocations": "activity.exercise-route-locations",
    ]
    static let sourceCanonicalTypes: [String: String] = [
        "HKDataTypeIdentifierAudiogram": "hearing.audiogram",
        "HKDataTypeIdentifierElectrocardiogram": "cardiac.electrocardiogram",
        "HKDataTypeStateOfMind": "mind.state",
        "HKMedicationDoseEventTypeIdentifierMedicationDoseEvent": "medication.dose",
        "HKWorkoutRouteTypeIdentifier": "activity.exercise-route",
    ]
    static let sourceCanonicalTypePrefixes: [String: String] = [
        "HKClinicalTypeIdentifier": "clinical.record",
    ]

    static func canonicalType(
        for sourceIdentifier: String,
        kind: String? = nil
    ) -> String {
        kind.flatMap { archiveOnlyCanonicalTypes[$0] }
            ?? canonicalTypesBySourceIdentifier[sourceIdentifier]
            ?? sourceCanonicalTypes[sourceIdentifier]
            ?? sourceCanonicalTypePrefixes.first(where: {
                sourceIdentifier.hasPrefix($0.key)
            })?.value
            ?? "archive.raw"
    }

    static func canonicalID(store: String, id: String) -> String {
        "\(store):\(id)"
    }

    static func canonicalID(for sourceID: String) -> String {
        canonicalID(store: sourceStore, id: sourceID)
    }
}
