#!/usr/bin/env bash
# Builds and installs Hozz on the maintainer's iPhone.
#
# Signing is injected here rather than committed, so the repository stays free
# of team identifiers. The injection is always reverted, including when the
# build fails.
#
# Signing is automatic rather than pinned to a named profile. A manual profile
# has to be regenerated by hand every time an entitlement changes, and silently
# builds without the new capability until someone does — which is exactly how
# the App Group came to be enabled with the widget still showing nothing.
set -euo pipefail

DEVICE="${HOZZ_DEVICE:-CACB5C41-FBA6-5DE8-9868-98BBDF897991}"
TEAM="${HOZZ_TEAM:-N8Z5T4AK3X}"
BUNDLE_ID="${HOZZ_BUNDLE_ID:-com.thatcube.Hozz}"
DERIVED="${HOZZ_DERIVED:-/tmp/hozz-dd}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

cp project.yml /tmp/hozz-project.yml.orig
restore() {
  cp /tmp/hozz-project.yml.orig project.yml
  rm -f /tmp/hozz-project.yml.orig
  xcodegen generate >/dev/null 2>&1
}
trap restore EXIT

# The widget can only show live state through a shared App Group container, but
# declaring that entitlement while the profile lacks it fails the build
# outright. So it is detected rather than assumed: the entitlement is injected
# only once a profile for this app actually grants the group. Registering the
# capability with Apple is the only manual step; nothing here needs editing.
APP_GROUP="${HOZZ_APP_GROUP:-group.com.thatcube.Hozz}"
HAS_APP_GROUP=0
for dir in "$HOME/Library/Developer/Xcode/UserData/Provisioning Profiles" \
           "$HOME/Library/MobileDevice/Provisioning Profiles"; do
  [ -d "$dir" ] || continue
  for candidate in "$dir"/*.mobileprovision; do
    [ -e "$candidate" ] || continue
    decoded="$(security cms -D -i "$candidate" 2>/dev/null || true)"
    case "$decoded" in
      *"<string>$TEAM.$BUNDLE_ID</string>"*) ;;
      *) continue ;;
    esac
    case "$decoded" in
      *"<string>$APP_GROUP</string>"*) HAS_APP_GROUP=1 ;;
    esac
  done
done

if [ "$HAS_APP_GROUP" -eq 1 ]; then
  echo "App Group $APP_GROUP is provisioned; the widget will show live state."
else
  echo "App Group $APP_GROUP is not provisioned for $BUNDLE_ID, so the widget"
  echo "will show a prompt instead of live state. Nothing else is affected."
  echo "To enable it: add the App Groups capability ($APP_GROUP) to both the"
  echo "Hozz and HozzWidget targets in Xcode."
fi

TEAM="$TEAM" APP_GROUP="$APP_GROUP" \
  HAS_APP_GROUP="$HAS_APP_GROUP" python3 - <<'PY'
import os
team = os.environ["TEAM"]
app_group = os.environ["APP_GROUP"]
has_app_group = os.environ["HAS_APP_GROUP"] == "1"
text = open("project.yml").read()

app_anchor = "        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor"
text = text.replace(app_anchor, app_anchor + f"""
      configs:
        Debug:
          DEVELOPMENT_TEAM: {team}
          CODE_SIGN_STYLE: Automatic""", 1)

# The widget is signed too, or the app it is embedded in will not build. The
# anchor is the last key of the widget's `base` block, so `configs` lands as a
# sibling of `base` rather than inside it.
widget_anchor = """    info:
      path: Widget/Info.plist"""
text = text.replace(widget_anchor, f"""      configs:
        Debug:
          DEVELOPMENT_TEAM: {team}
          CODE_SIGN_STYLE: Automatic
""" + widget_anchor, 1)

if has_app_group:
    # Both sides must declare the same group: the app writes the store and the
    # widget reads it, so granting only one of them changes nothing.
    app_entitlement = "        com.apple.developer.healthkit.access: []"
    text = text.replace(app_entitlement, app_entitlement + f"""
        com.apple.security.application-groups:
          - {app_group}""", 1)

    widget_info = """    info:
      path: Widget/Info.plist"""
    text = text.replace(widget_info, f"""    entitlements:
      path: Widget/HozzWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - {app_group}
""" + widget_info, 1)

open("project.yml", "w").write(text)
PY
xcodegen generate >/dev/null
DEVELOPER_DIR=/Applications/Xcode.app xcodebuild \
  -project Hozz.xcodeproj -scheme Hozz -configuration Debug \
  -destination "platform=iOS,id=$DEVICE" \
  -derivedDataPath "$DERIVED" -allowProvisioningUpdates build "$@"

APP="$DERIVED/Build/Products/Debug-iphoneos/Hozz.app"
xcrun devicectl device install app --device "$DEVICE" "$APP"
echo "Installed $(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP/Info.plist")"
