#!/usr/bin/env python3

import os
import pathlib
import re
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Sources/HozzCatalog/GeneratedHealthTypeCatalog.swift"
FAMILIES = {
    "HKQuantityTypeIdentifier": ("quantity", "HKTypeIdentifiers.h"),
    "HKCategoryTypeIdentifier": ("category", "HKTypeIdentifiers.h"),
    "HKCharacteristicTypeIdentifier": ("characteristic", "HKTypeIdentifiers.h"),
    "HKCorrelationTypeIdentifier": ("correlation", "HKTypeIdentifiers.h"),
    "HKClinicalTypeIdentifier": ("clinical", "HKClinicalType.h"),
    "HKDocumentTypeIdentifier": ("document", "HKTypeIdentifiers.h"),
    "HKScoredAssessmentTypeIdentifier": ("scoredAssessment", "HKTypeIdentifiers.h"),
}
QUANTITY_UNIT_OVERRIDES = {
    "HKQuantityTypeIdentifierUVExposure": "count",
}
KNOWN_QUANTITY_UNITS = {
    "%",
    "IU",
    "L",
    "L/min",
    "S",
    "W",
    "appleEffortScore",
    "cm",
    "count",
    "count/min",
    "count/s",
    "dBASPL",
    "degC",
    "g",
    "kcal",
    "kcal/(kg*hr)",
    "kg",
    "m",
    "m/s",
    "mL",
    "mg/dL",
    "min",
    "ml/(kg*min)",
    "mmHg",
    "ms",
}


def sdk_path() -> pathlib.Path:
    value = subprocess.check_output(
        ["xcrun", "--sdk", "iphoneos", "--show-sdk-path"],
        text=True,
    ).strip()
    return pathlib.Path(value)


def parse_version(attributes: str) -> tuple[int, int]:
    match = re.search(r"ios\((\d+)\.(\d+)", attributes)
    if not match:
        raise ValueError(f"Missing iOS availability in: {attributes}")
    return int(match.group(1)), int(match.group(2))


def parse_entries() -> list[dict[str, object]]:
    headers = (
        sdk_path()
        / "System/Library/Frameworks/HealthKit.framework/Headers"
    )
    entries: list[dict[str, object]] = []

    for prefix, (family, filename) in FAMILIES.items():
        text = (headers / filename).read_text()
        pattern = re.compile(
            rf"HK_EXTERN\s+{prefix}\s+const\s+({prefix}[A-Za-z0-9_]+)"
            rf"\s+([^;]+);([^\n]*)"
        )
        for match in pattern.finditer(text):
            attributes = match.group(2)
            major, minor = parse_version(attributes)
            comment = match.group(3).strip().removeprefix("//").strip()
            unit = None
            if family == "quantity" and comment:
                unit = comment.split(",", 1)[0].strip()
            if family == "quantity":
                unit = QUANTITY_UNIT_OVERRIDES.get(match.group(1), unit)
                if unit not in KNOWN_QUANTITY_UNITS:
                    raise ValueError(
                        f"Unknown canonical unit for {match.group(1)}: {unit!r}"
                    )
            entries.append(
                {
                    "identifier": match.group(1),
                    "family": family,
                    "major": major,
                    "minor": minor,
                    "unit": unit,
                    "deprecated": "API_DEPRECATED" in attributes,
                }
            )

    return sorted(entries, key=lambda entry: str(entry["identifier"]))


def swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render(entries: list[dict[str, object]]) -> str:
    lines = [
        "// Generated by tools/generate-healthkit-catalog.py. Do not edit.",
        "",
        "import Foundation",
        "",
        "enum GeneratedHealthTypeCatalog {",
        "    static let entries: [HealthCatalogEntry] = [",
    ]
    for entry in entries:
        unit = (
            f'"{swift_string(str(entry["unit"]))}"'
            if entry["unit"]
            else "nil"
        )
        lines.extend(
            [
                "        HealthCatalogEntry(",
                f'            identifier: "{entry["identifier"]}",',
                f'            family: .{entry["family"]},',
                "            introduced: IOSVersion("
                f'major: {entry["major"]}, minor: {entry["minor"]}),',
                f"            canonicalUnit: {unit},",
                f'            isDeprecated: {str(entry["deprecated"]).lower()}',
                "        ),",
            ]
        )
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def exec_under_build_lease() -> None:
    """Restart through the shared wrapper before reading the Apple SDK."""
    if os.environ.get("HOZZ_CATALOG_BUILD_LEASE_WRAPPED") == "1":
        required = (
            "APPLE_BUILD_LEASE_MODE",
            "APPLE_BUILD_LEASE_OWNER",
            "APPLE_BUILD_LEASE_ID",
            "APPLE_BUILD_LEASE_TOKEN",
            "APPLE_BUILD_LEASE_LOCK_FD",
            "APPLE_BUILD_LEASE_PROOF_FD",
        )
        if (
            os.environ.get("APPLE_BUILD_LEASE_PROTOCOL") != "1"
            or os.environ.get("APPLE_BUILD_LEASE_MODE") != "shared"
            or any(not os.environ.get(name) for name in required)
        ):
            sys.exit("Invalid inherited Apple build lease environment.")
        try:
            lock_fd = int(os.environ["APPLE_BUILD_LEASE_LOCK_FD"])
            proof_fd = int(os.environ["APPLE_BUILD_LEASE_PROOF_FD"])
        except ValueError:
            sys.exit("Invalid inherited Apple build lease descriptors.")
        if lock_fd < 3 or proof_fd < 3 or lock_fd == proof_fd:
            sys.exit("Invalid inherited Apple build lease descriptors.")

        validator = ROOT / "tools/lib/apple_build_lease.py"
        result = subprocess.run(
            [
                "/usr/bin/python3",
                str(validator),
                "validate",
                "--mode",
                "shared",
                "--owner",
                os.environ["APPLE_BUILD_LEASE_OWNER"],
                "--lease-id",
                os.environ["APPLE_BUILD_LEASE_ID"],
                "--token",
                os.environ["APPLE_BUILD_LEASE_TOKEN"],
                "--lock-fd",
                str(lock_fd),
                "--proof-fd",
                str(proof_fd),
                "--role-exit-code",
            ],
            pass_fds=(proof_fd, lock_fd),
            check=False,
        )
        if result.returncode not in {0, 10}:
            sys.exit("Inherited Apple build lease validation failed.")
        return

    wrapper = ROOT / "tools/with-apple-build-lease.sh"
    env = dict(os.environ)
    env["HOZZ_CATALOG_BUILD_LEASE_WRAPPED"] = "1"
    os.execve(
        wrapper,
        [
            str(wrapper),
            "hozz/generate-healthkit-catalog",
            "--",
            sys.executable,
            str(pathlib.Path(__file__).resolve()),
            *sys.argv[1:],
        ],
        env,
    )


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(parse_entries()))
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    exec_under_build_lease()
    main()
